### ISSUE TITLE
Epic: Proxy

### ISSUE THREAD

**Issue by Chaostheorie** [Chaostheorie/harmonia#1]
- [ ] Implement fetching from upstreams for all routes
- [ ] Implement mt fetching with interrupt of other requests
- [ ] Implement signature validation for fetched upstream responses
- [ ] Implement resigning upstream respones
- [ ] extend nixos module for new configuration options
  - [ ] use `config.nix.settings.trusted-{..}` as default
- [ ] upstream it
